/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unina.db2019.operations;

import it.unina.db2019.project.DBOperation;
import it.unina.db2019.project.DBConnection;
import it.unina.db2019.project.DBOperation;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import  javax.swing.event.*;

/**
 *
 * @author Sysken
 */
public class Composizione extends DefaultFrame {
    
    private Object bean;

    /**
     * Creates new customizer Composizione
     */
    public Composizione() {
        initComponents();
        setFrameTable(jTableComposizione);
        setNomeTabella("COMPOSIZIONE");
        jTextFieldStrutturato.setEnabled(false);
        jTextFieldTipo.setEnabled(false);  
        this.setLocationRelativeTo(null);
        jTableComposizione.setFocusable(false);
        Aggiorna();     
        jTableComposizione.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                if(jTableComposizione.getSelectedRow() != -1){
                    getInfo();
                }
            }
        }); 
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStrutturato = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jTextFieldStrutturato = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableComposizione = new javax.swing.JTable();

        setTitle("UML STORAGE - COMPOSIZIONE");
        setMinimumSize(new java.awt.Dimension(0, 490));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelStrutturato.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelStrutturato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/db2019/operations/fk.png"))); // NOI18N
        jLabelStrutturato.setText("| Strutturato:");

        jLabelTipo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/db2019/operations/fk.png"))); // NOI18N
        jLabelTipo.setText("| Tipo:");

        jTextFieldStrutturato.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldStrutturato.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldTipo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableComposizione.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableComposizione.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableComposizione);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTipo)
                            .addComponent(jLabelStrutturato))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldStrutturato, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jTextFieldTipo)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStrutturato)
                    .addComponent(jTextFieldStrutturato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setModalita(int modo){
        super.setModalita(modo);
        switch (modo) {
           case INSERISCI:
              setEnabledjTextFieldPK(true);
              jTextFieldStrutturato.setEnabled(true);
              jTextFieldTipo.setEnabled(true);
              break;
           case MODIFICA:
              setEnabledjTextFieldPK(false);
              jTextFieldStrutturato.setEnabled(true);
              jTextFieldTipo.setEnabled(true);
              break;
           case ELIMINA:
              setEnabledjTextFieldPK(false);
              jTextFieldStrutturato.setEnabled(false);
              jTextFieldTipo.setEnabled(false);
              break;
           case RICERCA:
              setEnabledjTextFieldPK(true);
              jTextFieldStrutturato.setEnabled(true);
              jTextFieldTipo.setEnabled(true);
              break;
        }
    }

    @Override
    protected PreparedStatement selectAll(){
        Connection con;
        PreparedStatement st = null;
        super.selectAll();
        query = query + "ORDER BY ID_COMPOSIZIONE ";
        try {
           con = DBConnection.getConnection();
           st = con.prepareStatement(query, ResultSet.TYPE_SCROLL_INSENSITIVE,
                   ResultSet.CONCUR_READ_ONLY); 
        } catch (SQLException e) {
        }
        return st;
    }

    @Override
    protected void pulisci(){
        super.pulisci();
        jTextFieldStrutturato.setText("");
        jTextFieldTipo.setText("");
        jTableComposizione.clearSelection();
        super.setFocusPK();
    }

    @Override
    protected void getInfo(){
        selectedRow = jTableComposizione.getSelectedRow();
        setJTextFieldPK((jTableComposizione.getValueAt(selectedRow, 0)).toString());
        jTextFieldStrutturato.setText((String)jTableComposizione.getValueAt(selectedRow, 1).toString());
        jTextFieldTipo.setText((jTableComposizione.getValueAt(selectedRow, 2)).toString());
    }

    @Override
    protected void Aggiorna(){
        PreparedStatement st = selectAll();
        eseguiQuery(st);
    }

    @Override
    protected PreparedStatement opInserisci(Connection c)
           throws SQLException{
                String cmdIns;
        PreparedStatement st;
        cmdIns = "insert into " + DBConnection.schema + ".COMPOSIZIONE (ID_Composizione,FK_Strutturato,"
                + "FK_Tipo)  values(?,?,?)";
        st = c.prepareStatement(cmdIns);
        if(getCodice().getText().equals("")){
            st.setNull(1, Types.INTEGER);
        } else{
            st.setInt(1, Integer.valueOf(getCodice().getText()));
        }
        st.setInt(2, Integer.valueOf(jTextFieldStrutturato.getText()));
        st.setInt(3, Integer.valueOf(jTextFieldTipo.getText()));
        return st;
    }

    @Override
    protected PreparedStatement opModifica(Connection c)
           throws SQLException{
        PreparedStatement st = null;
        if(!getCodice().getText().equals("")){
          String cmdUp;
          cmdUp = "update " + DBConnection.schema + ".COMPOSIZIONE "
                          + " set FK_Strutturato = ?, " 
                          + "     FK_Tipo = ? "
                          + "where     ID_Composizione = ? ";;
          st = c.prepareStatement(cmdUp);
          st.setInt(1, Integer.valueOf(jTextFieldStrutturato.getText()));
          st.setInt(2, Integer.valueOf(jTextFieldTipo.getText()));
          st.setInt(3, Integer.valueOf(getCodice().getText()));
        } else{
              JOptionPane.showMessageDialog(this, "Nessun record selezionato!",
                                            "Errore", JOptionPane.ERROR_MESSAGE);
        }
        return st;
    }

    @Override
    protected PreparedStatement opRicerca(Connection c)
           throws SQLException{
        PreparedStatement st = null;
        String cmdSrc;
        int index = 1;
        Pattern pat;
        Matcher match;
        cmdSrc = "select * from " + DBConnection.schema + ".COMPOSIZIONE where";
        if (getCodice().getText().length() > 0) {
           cmdSrc += " ID_Composizione = ? and";
        }
        if (jTextFieldStrutturato.getText().length() > 0) {
           cmdSrc += " FK_Strutturato = ? and";
        }
        if (jTextFieldTipo.getText().length() > 0) {
           cmdSrc += " FK_Tipo = ? and";
        }
        pat = Pattern.compile("(where|and)$"); 
        match = pat.matcher(cmdSrc);
        cmdSrc = match.replaceAll("");
        cmdSrc += " ORDER BY ID_COMPOSIZIONE";
        try {
           st = c.prepareStatement(cmdSrc, ResultSet.TYPE_SCROLL_INSENSITIVE,
                   ResultSet.CONCUR_READ_ONLY); 
        } catch (SQLException e) {
        }
        if(st != null){
          if (getCodice().getText().length() > 0) {
              st.setInt(index++, Integer.valueOf(getCodice().getText()));
          }
          if (jTextFieldStrutturato.getText().length() > 0) {
              st.setInt(index++, Integer.valueOf(jTextFieldStrutturato.getText()));
          }
          if (jTextFieldTipo.getText().length() > 0) {
              st.setInt(index++, Integer.valueOf(jTextFieldTipo.getText()));
          }
        }
        return st; 
    }

    @Override
    protected PreparedStatement opElimina(Connection c)
           throws SQLException{
        PreparedStatement st = null;
        if(!getCodice().getText().equals("")){
            String cmdDel;
            cmdDel = "delete from " + DBConnection.schema + ".COMPOSIZIONE where "
                      + "ID_Composizione = ? ";
            st = c.prepareStatement(cmdDel);
            st.setInt(1, Integer.valueOf(getCodice().getText()));
        } else{
            JOptionPane.showMessageDialog(this, "Nessun record selezionato!",
                                          "Errore", JOptionPane.ERROR_MESSAGE);
        }
        return st;
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DBOperation.currentlyOpen[12] = null;
    }//GEN-LAST:event_formWindowClosing

   @Override
    protected void reselectPrevRow(){
        if(jTableComposizione.getRowCount() > 0){
            switch(getModalita()){
                case MODIFICA:
                    jTableComposizione.setRowSelectionInterval(selectedRow, selectedRow);
                    break;
                case INSERISCI:
                    jTableComposizione.setRowSelectionInterval(jTableComposizione.getRowCount()-1, jTableComposizione.getRowCount()-1);
                    break;
                case ELIMINA:
                    if(selectedRow < jTableComposizione.getRowCount()){
                            jTableComposizione.setRowSelectionInterval(selectedRow, selectedRow);
                    } else{
                        jTableComposizione.setRowSelectionInterval(selectedRow-1, selectedRow-1);
                    }     
            }
        }    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelStrutturato;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableComposizione;
    private javax.swing.JTextField jTextFieldStrutturato;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
