/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unina.db2019.operations;

import it.unina.db2019.project.DBConnection;
import it.unina.db2019.project.DBOperation;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import  javax.swing.event.*;

/**
 *
 * @author Sysken
 */
public class Parametro extends DefaultFrame {
    
    private Object bean;

    /**
     * Creates new customizer Parametro
     */
    public Parametro() {
        initComponents();
        this.setLocationRelativeTo(null);
        setFrameTable(jTableParametro);
        setNomeTabella("PARAMETRO");
        jTextFieldNome.setEnabled(false);
        jTextFieldPosizione.setEnabled(false);
        jTextFieldClasse.setEnabled(false);
        jTextFieldMetodo.setEnabled(false);
        jTextFieldTipo.setEnabled(false);
        jTableParametro.setFocusable(false);
        Aggiorna();     
        jTableParametro.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                if(jTableParametro.getSelectedRow() != -1){
                    getInfo();
                }
            }
        }); 
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jLabelPosizione = new javax.swing.JLabel();
        jLabelClasse = new javax.swing.JLabel();
        jLabelMetodo = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldPosizione = new javax.swing.JTextField();
        jTextFieldClasse = new javax.swing.JTextField();
        jTextFieldMetodo = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableParametro = new javax.swing.JTable();

        setTitle("UML STORAGE - PARAMETRO");
        setMinimumSize(new java.awt.Dimension(0, 630));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelNome.setText("Nome:");

        jLabelPosizione.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelPosizione.setText("Posizione:");

        jLabelClasse.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelClasse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/db2019/operations/fk.png"))); // NOI18N
        jLabelClasse.setText("| Classe:");

        jLabelMetodo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelMetodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/db2019/operations/fk.png"))); // NOI18N
        jLabelMetodo.setText("| Metodo:");

        jLabelTipo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/db2019/operations/fk.png"))); // NOI18N
        jLabelTipo.setText("| Tipo:");

        jTextFieldNome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldPosizione.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldPosizione.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldClasse.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldClasse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldMetodo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMetodo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldTipo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableParametro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableParametro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMetodo)
                            .addComponent(jLabelTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClasse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPosizione, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jTextFieldPosizione)
                            .addComponent(jTextFieldClasse)
                            .addComponent(jTextFieldMetodo)
                            .addComponent(jTextFieldTipo))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosizione)
                    .addComponent(jTextFieldPosizione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClasse)
                    .addComponent(jTextFieldClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMetodo)
                    .addComponent(jTextFieldMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setModalita(int modo){
        super.setModalita(modo);
        switch (modo) {
           case INSERISCI:
              setEnabledjTextFieldPK(true);
              jTextFieldNome.setEnabled(true);
              jTextFieldPosizione.setEnabled(true);
              jTextFieldClasse.setEnabled(true);
              jTextFieldMetodo.setEnabled(true);
              jTextFieldTipo.setEnabled(true);  
              break;
           case MODIFICA:
              setEnabledjTextFieldPK(false);
              jTextFieldNome.setEnabled(true);
              jTextFieldPosizione.setEnabled(true);
              jTextFieldClasse.setEnabled(false);
              jTextFieldMetodo.setEnabled(false);
              jTextFieldTipo.setEnabled(true);             
              break;
           case ELIMINA:
              setEnabledjTextFieldPK(false);
              jTextFieldNome.setEnabled(false);
              jTextFieldPosizione.setEnabled(false);
              jTextFieldClasse.setEnabled(false);
              jTextFieldMetodo.setEnabled(false);
              jTextFieldTipo.setEnabled(false);                 
              break;
           case RICERCA:      
              setEnabledjTextFieldPK(true);
              jTextFieldNome.setEnabled(true);
              jTextFieldPosizione.setEnabled(true);
              jTextFieldClasse.setEnabled(true);
              jTextFieldMetodo.setEnabled(true);
              jTextFieldTipo.setEnabled(true);  
              break;
        }
    }

    @Override
    protected PreparedStatement selectAll(){
        Connection con;
        PreparedStatement st = null;
        super.selectAll();
        query = query + "ORDER BY ID_PARAMETRO ";
        try {
           con = DBConnection.getConnection();
           st = con.prepareStatement(query, ResultSet.TYPE_SCROLL_INSENSITIVE,
                   ResultSet.CONCUR_READ_ONLY); 
        } catch (SQLException e) {
        }
        return st;
    }

    @Override
    protected void pulisci(){
        super.pulisci();
        jTextFieldNome.setText("");
        jTextFieldPosizione.setText("");
        jTextFieldClasse.setText("");
        jTextFieldMetodo.setText("");
        jTextFieldTipo.setText("");
        jTableParametro.clearSelection();
        super.setFocusPK();
    }

    @Override
    protected void getInfo(){
        selectedRow = jTableParametro.getSelectedRow();
        setJTextFieldPK((jTableParametro.getValueAt(selectedRow, 0)).toString());
        jTextFieldNome.setText((String)jTableParametro.getValueAt(selectedRow, 1));
        jTextFieldPosizione.setText((String)jTableParametro.getValueAt(selectedRow, 2).toString());
        if((jTableParametro.getValueAt(selectedRow, 3) != null)){
            jTextFieldClasse.setText((jTableParametro.getValueAt(selectedRow, 3)).toString());
        } else{
            jTextFieldClasse.setText("");
        }
        if((jTableParametro.getValueAt(selectedRow, 4) != null)){
            jTextFieldMetodo.setText((jTableParametro.getValueAt(selectedRow, 4)).toString());
        } else{
            jTextFieldMetodo.setText("");
        }
        if((jTableParametro.getValueAt(selectedRow, 5) != null)){
            jTextFieldTipo.setText((jTableParametro.getValueAt(selectedRow, 5)).toString());
        } else{
            jTextFieldTipo.setText("");
        }
    }

    @Override
    protected void Aggiorna(){
        PreparedStatement st = selectAll();
        eseguiQuery(st);
    }

    @Override
    protected PreparedStatement opInserisci(Connection c)
           throws SQLException{
        String cmdIns;
        PreparedStatement st;
        cmdIns = "insert into " + DBConnection.schema + ".PARAMETRO (ID_Parametro,Nome,"
                + "Posizione, FK_Classe, FK_Metodo, FK_Tipo)  values(?,?,?,?,?,?)";
        st = c.prepareStatement(cmdIns);
        if(getCodice().getText().equals("")){
            st.setNull(1, Types.INTEGER);
        } else{
            st.setInt(1, Integer.valueOf(getCodice().getText()));
        }
        st.setString(2, jTextFieldNome.getText());
        st.setInt(3, Integer.valueOf(jTextFieldPosizione.getText()));
        if(jTextFieldClasse.getText().equals("")){
          st.setNull(4, Types.VARCHAR);
        } else{
          st.setInt(4, Integer.valueOf(jTextFieldClasse.getText()));
        }
        if(jTextFieldMetodo.getText().equals("")){
          st.setNull(5, Types.VARCHAR);
        } else{
          st.setInt(5, Integer.valueOf(jTextFieldMetodo.getText()));
        }
       if(jTextFieldTipo.getText().equals("")){
          st.setNull(6, Types.VARCHAR);
        } else{
          st.setInt(6, Integer.valueOf(jTextFieldTipo.getText()));
        }
        return st;
    }

    @Override
    protected PreparedStatement opModifica(Connection c)
           throws SQLException{
        PreparedStatement st = null;
        if(!getCodice().getText().equals("")){
            String cmdUp;
            cmdUp = "update " + DBConnection.schema + ".PARAMETRO "
                            + " set Nome = ?, " 
                            + "     Posizione = ?, "
                            + "     FK_Tipo = ? "
                            + " where ID_Parametro = ? ";
            st = c.prepareStatement(cmdUp);
            st.setString(1, jTextFieldNome.getText());
            st.setInt(2, Integer.valueOf(jTextFieldPosizione.getText()));
            if(jTextFieldTipo.getText().equals("")){
                st.setNull(3, Types.VARCHAR);
            } else{
                st.setInt(3, Integer.valueOf(jTextFieldTipo.getText()));
            }
            st.setInt(4, Integer.valueOf(getCodice().getText()));
        } else{
            JOptionPane.showMessageDialog(this, "Nessun record selezionato!",
                                          "Errore", JOptionPane.ERROR_MESSAGE);
        }
        return st;
    }

    @Override
    protected PreparedStatement opRicerca(Connection c)
           throws SQLException{
        PreparedStatement st = null;
        String cmdSrc;
        int index = 1;
        Pattern pat;
        Matcher match;
        String descrizione;
        cmdSrc = "select * from " + DBConnection.schema + ".PARAMETRO where";
        if (getCodice().getText().length() > 0) {
           cmdSrc += " ID_Parametro = ? and";
        }
        if (jTextFieldNome.getText().length() > 0) {
           cmdSrc += " Nome = ? and";
        }
        if (jTextFieldPosizione.getText().length() > 0) {
           cmdSrc += " Posizione = ? and";
        }
        if (jTextFieldClasse.getText().length() > 0) {
           cmdSrc += " FK_Classe = ? and";
        }
        if(jTextFieldMetodo.getText().length() > 0){
            cmdSrc += " FK_Metodo = ? and";
        }
        if (jTextFieldTipo.getText().length() > 0) {
           cmdSrc += " FK_Tipo = ? and";
        }
        pat = Pattern.compile("(where|and)$"); 
        match = pat.matcher(cmdSrc);
        cmdSrc = match.replaceAll("");
        cmdSrc += " ORDER BY ID_PARAMETRO";
        try {
           st = c.prepareStatement(cmdSrc, ResultSet.TYPE_SCROLL_INSENSITIVE,
                   ResultSet.CONCUR_READ_ONLY); 
        } catch (SQLException e) {
        }
        if(st != null){
            if (getCodice().getText().length() > 0) {
               st.setInt(index++, Integer.valueOf(getCodice().getText()));
            }
            if (jTextFieldNome.getText().length() > 0) {
               st.setString(index++, jTextFieldNome.getText());
            }
            if (jTextFieldPosizione.getText().length() > 0) {
               st.setInt(index++, Integer.valueOf(jTextFieldPosizione.getText()));
            }
            if (jTextFieldClasse.getText().length() > 0) {
               st.setInt(index++, Integer.valueOf(jTextFieldClasse.getText()));
            }
            if(jTextFieldMetodo.getText().length() > 0){
               st.setInt(index++, Integer.valueOf(jTextFieldMetodo.getText()));
            }
            if (jTextFieldTipo.getText().length() > 0) {
               st.setInt(index++, Integer.valueOf(jTextFieldTipo.getText()));
            }
        }
        return st;
    }

    @Override
    protected PreparedStatement opElimina(Connection c)
           throws SQLException{
        PreparedStatement st = null;
        if(!getCodice().getText().equals("")){
            String cmdDel;
            cmdDel = "delete from " + DBConnection.schema + ".PARAMETRO where "
                      + "ID_Parametro = ? ";
            st = c.prepareStatement(cmdDel);
            st.setInt(1, Integer.valueOf(getCodice().getText()));
        } else{
            JOptionPane.showMessageDialog(this, "Nessun record selezionato!",
                                          "Errore", JOptionPane.ERROR_MESSAGE);
        }
        return st;
    }
    
    @Override
    protected void reselectPrevRow(){
        if(jTableParametro.getRowCount() > 0){
            switch(getModalita()){
                case MODIFICA:
                    jTableParametro.setRowSelectionInterval(selectedRow, selectedRow);
                    break;
                case INSERISCI:
                    jTableParametro.setRowSelectionInterval(jTableParametro.getRowCount()-1, jTableParametro.getRowCount()-1);
                    break;
                case ELIMINA:
                    if(selectedRow < jTableParametro.getRowCount()){
                            jTableParametro.setRowSelectionInterval(selectedRow, selectedRow);
                    } else{
                        jTableParametro.setRowSelectionInterval(selectedRow-1, selectedRow-1);
                    }     
            }
        }    
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DBOperation.currentlyOpen[6] = null;
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelClasse;
    private javax.swing.JLabel jLabelMetodo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPosizione;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableParametro;
    private javax.swing.JTextField jTextFieldClasse;
    private javax.swing.JTextField jTextFieldMetodo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPosizione;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
