/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unina.db2019.operations;

import it.unina.db2019.project.DBConnection;
import it.unina.db2019.project.DBOperation;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.event.*;

/**
 *
 * @author Sysken
 */
public class Qualificazione extends DefaultFrame {
    
    private Object bean;

    /**
     * Creates new customizer Qualificazione
     */
    public Qualificazione() {
        initComponents();
        setFrameTable(jTableQualificazione);
        setNomeTabella("QUALIFICAZIONE");
        jTextFieldAttributo.setEnabled(false);
        jTextFieldPart.setEnabled(false);  
        this.setLocationRelativeTo(null);
        jTableQualificazione.setFocusable(false);
        Aggiorna();     
        jTableQualificazione.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                if(jTableQualificazione.getSelectedRow() != -1){
                    getInfo();
                }
            }
        }); 
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPart = new javax.swing.JLabel();
        jLabelAttributo = new javax.swing.JLabel();
        jTextFieldPart = new javax.swing.JTextField();
        jTextFieldAttributo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableQualificazione = new javax.swing.JTable();

        setTitle("UML STORAGE - QUALIFICAZIONE");
        setMinimumSize(new java.awt.Dimension(0, 490));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelPart.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelPart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/db2019/operations/fk.png"))); // NOI18N
        jLabelPart.setText("| Partecipazione:");

        jLabelAttributo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelAttributo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/db2019/operations/fk.png"))); // NOI18N
        jLabelAttributo.setText("| Attributo:");

        jTextFieldPart.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldPart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldAttributo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldAttributo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableQualificazione.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQualificazione.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableQualificazione);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAttributo)
                            .addComponent(jLabelPart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPart, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(jTextFieldAttributo)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPart)
                    .addComponent(jTextFieldPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAttributo)
                    .addComponent(jTextFieldAttributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DBOperation.currentlyOpen[10] = null;
    }//GEN-LAST:event_formWindowClosing

    @Override
    public void setModalita(int modo){
        super.setModalita(modo);
        switch (modo) {
           case INSERISCI:
              setEnabledjTextFieldPK(true);
              jTextFieldAttributo.setEnabled(true);
              jTextFieldPart.setEnabled(true);
              break;
           case MODIFICA:
              setEnabledjTextFieldPK(false);
              jTextFieldAttributo.setEnabled(true);
              jTextFieldPart.setEnabled(true);
              break;
           case ELIMINA:
              setEnabledjTextFieldPK(false);
              jTextFieldAttributo.setEnabled(false);
              jTextFieldPart.setEnabled(false);
              break;
           case RICERCA:
              setEnabledjTextFieldPK(true);
              jTextFieldAttributo.setEnabled(true);
              jTextFieldPart.setEnabled(true);
              break;
        }
    }

    @Override
    protected PreparedStatement selectAll(){
        Connection con;
        PreparedStatement st = null;
        super.selectAll();
        query = query + "ORDER BY ID_QUALIFICAZIONE ";
        try {
           con = DBConnection.getConnection();
           st = con.prepareStatement(query, ResultSet.TYPE_SCROLL_INSENSITIVE,
                   ResultSet.CONCUR_READ_ONLY); 
        } catch (SQLException e) {
        }
        return st;
    }

    @Override
    protected void pulisci(){
        super.pulisci();
        jTextFieldPart.setText("");
        jTextFieldAttributo.setText("");
        jTableQualificazione.clearSelection();
        super.setFocusPK();
    }

    @Override
    protected void getInfo(){
        selectedRow = jTableQualificazione.getSelectedRow();
        setJTextFieldPK((jTableQualificazione.getValueAt(selectedRow, 0)).toString());
        jTextFieldPart.setText((String)jTableQualificazione.getValueAt(selectedRow, 1).toString());
        jTextFieldAttributo.setText((jTableQualificazione.getValueAt(selectedRow, 2)).toString());
    }

    @Override
    protected void Aggiorna(){
        PreparedStatement st = selectAll();
        eseguiQuery(st);
    }

    @Override
    protected PreparedStatement opInserisci(Connection c)
           throws SQLException{
        String cmdIns;
        PreparedStatement st;
        cmdIns = "insert into " + DBConnection.schema + ".QUALIFICAZIONE (ID_Qualificazione,FK_Partecipazione,"
                + "FK_Attributo)  values(?,?,?)";
        st = c.prepareStatement(cmdIns);
        if(getCodice().getText().equals("")){
            st.setNull(1, Types.INTEGER);
        } else{
            st.setInt(1, Integer.valueOf(getCodice().getText()));
        }
        st.setInt(2, Integer.valueOf(jTextFieldPart.getText()));
        st.setInt(3, Integer.valueOf(jTextFieldAttributo.getText()));
        return st;
    }

    @Override
    protected PreparedStatement opModifica(Connection c)
           throws SQLException{
        PreparedStatement st = null;
        if(!getCodice().getText().equals("")){
          String cmdUp;
          cmdUp = "update " + DBConnection.schema + ".QUALIFICAZIONE "
                          + " set FK_Partecipazione = ?, " 
                          + "     FK_Attributo = ? "
                          + "where     ID_Qualificazione = ? ";;
          st = c.prepareStatement(cmdUp);
          st.setInt(1, Integer.valueOf(jTextFieldPart.getText()));
          st.setInt(2, Integer.valueOf(jTextFieldAttributo.getText()));
          st.setInt(3, Integer.valueOf(getCodice().getText()));
        } else{
              JOptionPane.showMessageDialog(this, "Nessun record selezionato!",
                                            "Errore", JOptionPane.ERROR_MESSAGE);
        }
        return st;
    }

    @Override
    protected PreparedStatement opRicerca(Connection c)
           throws SQLException{
        PreparedStatement st = null;
        String cmdSrc;
        int index = 1;
        Pattern pat;
        Matcher match;
        cmdSrc = "select * from " + DBConnection.schema + ".QUALIFICAZIONE where";
        if (getCodice().getText().length() > 0) {
           cmdSrc += " ID_Qualificazione = ? and";
        }
        if (jTextFieldPart.getText().length() > 0) {
           cmdSrc += " FK_Partecipazione = ? and";
        }
        if (jTextFieldAttributo.getText().length() > 0) {
           cmdSrc += " FK_Attributo = ? and";
        }
        pat = Pattern.compile("(where|and)$"); 
        match = pat.matcher(cmdSrc);
        cmdSrc = match.replaceAll("");
        cmdSrc += " ORDER BY ID_QUALIFICAZIONE";
        try {
           st = c.prepareStatement(cmdSrc, ResultSet.TYPE_SCROLL_INSENSITIVE,
                   ResultSet.CONCUR_READ_ONLY); 
        } catch (SQLException e) {
        }
        if(st != null){
          if (getCodice().getText().length() > 0) {
              st.setInt(index++, Integer.valueOf(getCodice().getText()));
          }
          if (jTextFieldPart.getText().length() > 0) {
              st.setInt(index++, Integer.valueOf(jTextFieldPart.getText()));
          }
          if (jTextFieldAttributo.getText().length() > 0) {
              st.setInt(index++, Integer.valueOf(jTextFieldAttributo.getText()));
          }
        }
        return st;  
    }

    @Override
    protected PreparedStatement opElimina(Connection c)
           throws SQLException{
        PreparedStatement st = null;
        if(!getCodice().getText().equals("")){
            String cmdDel;
            cmdDel = "delete from " + DBConnection.schema + ".QUALIFICAZIONE where "
                      + "ID_Qualificazione = ? ";
            st = c.prepareStatement(cmdDel);
            st.setInt(1, Integer.valueOf(getCodice().getText()));
        } else{
            JOptionPane.showMessageDialog(this, "Nessun record selezionato!",
                                          "Errore", JOptionPane.ERROR_MESSAGE);
        }
        return st;
    }
    
    @Override
    protected void reselectPrevRow(){
        if(jTableQualificazione.getRowCount() > 0){
            switch(getModalita()){
                case MODIFICA:
                    jTableQualificazione.setRowSelectionInterval(selectedRow, selectedRow);
                    break;
                case INSERISCI:
                    jTableQualificazione.setRowSelectionInterval(jTableQualificazione.getRowCount()-1, jTableQualificazione.getRowCount()-1);
                    break;
                case ELIMINA:
                    if(selectedRow < jTableQualificazione.getRowCount()){
                            jTableQualificazione.setRowSelectionInterval(selectedRow, selectedRow);
                    } else{
                        jTableQualificazione.setRowSelectionInterval(selectedRow-1, selectedRow-1);
                    }     
            }
        }    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAttributo;
    private javax.swing.JLabel jLabelPart;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableQualificazione;
    private javax.swing.JTextField jTextFieldAttributo;
    private javax.swing.JTextField jTextFieldPart;
    // End of variables declaration//GEN-END:variables
}
