/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unina.db2019.project;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import org.jdesktop.beansbinding.Binding; 

/**
 *
 * @author Sysken
 */
public class Login extends javax.swing.JDialog {

    
    /**
     * Premuto il pulsante exit
     */
    final static public int ABORT = 0;

    /**
     * Premuto il pulsante login
     */
    final static public int LOGIN = 1;
    
    /**
     * Premuto il pulsante annulla
     */
    final static public int CLEAN = 2;
    
    /**
     * Errore nella connessione
     */
    final static public int ERR = 3;

    /**
     * Flag che indica il pulsante premuto
     */
    private int pressed; 
    
    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        jRadioButtonEqual.setFocusable(false);
        this.jTextFieldUser.requestFocus();
        defaultPressed();
    }

    /**
     * Setta il path dell'icona del jDialog
     */
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconCD.png")));
    }
    
    /**
     * Imposta il pulsante di default accessibile con Enter.
     */
    
    public int getPressed(){
      return pressed;
    }
    
    private void defaultPressed(){
      getRootPane().setDefaultButton(jButtonEnter);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabelLogin = new javax.swing.JLabel();
        jTextFieldHost = new javax.swing.JTextField();
        jTextFieldPort = new javax.swing.JTextField();
        jTextFieldSID = new javax.swing.JTextField();
        jTextFieldSchema = new javax.swing.JTextField();
        jTextFieldUser = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jRadioButtonEqual = new javax.swing.JRadioButton();
        jButtonEnter = new javax.swing.JButton();
        jButtonAbort = new javax.swing.JButton();
        jLabelHost = new javax.swing.JLabel();
        jLabelPort = new javax.swing.JLabel();
        jLabelSID = new javax.swing.JLabel();
        jLabelSchema = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UML STORAGE");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabelLogin.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(0, 153, 153));
        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogin.setText("Login");
        jLabelLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldHost.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldHost.setText("localhost");
        jTextFieldHost.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldPort.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldPort.setText("1521");
        jTextFieldPort.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldSID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldSID.setText("xe");
        jTextFieldSID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldSchema.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldSchema.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextFieldUser, org.jdesktop.beansbinding.ELProperty.create("${text}"), jTextFieldSchema, org.jdesktop.beansbinding.BeanProperty.create("text"), "bindSchema");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRadioButtonEqual, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), jTextFieldSchema, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jTextFieldUser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPasswordField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPasswordField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jRadioButtonEqual.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButtonEqual.setSelected(true);
        jRadioButtonEqual.setText("= User");
        jRadioButtonEqual.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonEqualStateChanged(evt);
            }
        });

        jButtonEnter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonEnter.setText("Invia");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jButtonAbort.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonAbort.setText("Annulla");
        jButtonAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbortActionPerformed(evt);
            }
        });

        jLabelHost.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelHost.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/db2019/project/host.png"))); // NOI18N
        jLabelHost.setText("| Host");

        jLabelPort.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelPort.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/db2019/project/port.png"))); // NOI18N
        jLabelPort.setText("| Porta");

        jLabelSID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelSID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/db2019/project/sid.png"))); // NOI18N
        jLabelSID.setText("| SID");

        jLabelSchema.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelSchema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSchema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/db2019/project/schema.png"))); // NOI18N
        jLabelSchema.setText("| Schema");

        jLabelUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/db2019/project/user.png"))); // NOI18N
        jLabelUser.setText("| User");

        jLabelPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/db2019/project/password.png"))); // NOI18N
        jLabelPassword.setText("| Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelHost)
                        .addGap(46, 46, 46)
                        .addComponent(jTextFieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelPort)
                        .addGap(41, 41, 41)
                        .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelSID)
                        .addGap(50, 50, 50)
                        .addComponent(jTextFieldSID, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelSchema)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldSchema, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButtonEqual))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelUser)
                        .addGap(46, 46, 46)
                        .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelPassword)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(jButtonAbort, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 70, Short.MAX_VALUE))
            .addComponent(jLabelLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelHost))
                    .addComponent(jTextFieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelPort))
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelSID))
                    .addComponent(jTextFieldSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelSchema))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSchema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonEqual))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUser)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelPassword))
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEnter)
                    .addComponent(jButtonAbort))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
       DBConnection.host = jTextFieldHost.getText();
       try {
          DBConnection.port = Integer.parseInt(jTextFieldPort.getText());
       } catch (NumberFormatException e) {
          JOptionPane.showMessageDialog(this, "La porta deve essere un numero!",
                                        "Errore", JOptionPane.ERROR_MESSAGE);
       }
       if(DBConnection.port < 0 || DBConnection.port > 65535){
          JOptionPane.showMessageDialog(this, "La porta deve essere compresa tra 0 e 65535!",
                                        "Errore", JOptionPane.ERROR_MESSAGE);
       }
       DBConnection.schema = jTextFieldSchema.getText();
       DBConnection.sid = jTextFieldSID.getText();
       DBConnection.user = jTextFieldUser.getText();
       DBConnection.password = new String(jPasswordField.getPassword());
       try {
          DBConnection.setConnection(DBConnection.newConnection());
          pressed = LOGIN;
          dispose();
       } catch (SQLException e) {
          // Database.mostraErroriSwing(this, e);
          JOptionPane.showMessageDialog(this, "Connessione fallita!",
                                        "Errore", JOptionPane.ERROR_MESSAGE);
          pressed = ERR;
          jPasswordField.setText("");
       }
    }//GEN-LAST:event_jButtonEnterActionPerformed

    private void jButtonAbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbortActionPerformed
        pressed = CLEAN;
        jTextFieldHost.setText("locahost");
        jTextFieldPort.setText("1521");
        jTextFieldSID.setText("xe");
        jTextFieldSchema.setText("");
        jTextFieldUser.setText("");
        jPasswordField.setText("");
    }//GEN-LAST:event_jButtonAbortActionPerformed

    private void jRadioButtonEqualStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonEqualStateChanged
     
      Binding legame = bindingGroup.getBinding("bindSchema");
      if (legame.isBound()) {
         legame.unbind();
      } else {
         legame.bind();
      }
     
    }//GEN-LAST:event_jRadioButtonEqualStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(pressed != LOGIN){
            pressed = ABORT;
        }
    }//GEN-LAST:event_formWindowClosed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbort;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JLabel jLabelHost;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelSID;
    private javax.swing.JLabel jLabelSchema;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JRadioButton jRadioButtonEqual;
    private javax.swing.JTextField jTextFieldHost;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldSID;
    private javax.swing.JTextField jTextFieldSchema;
    private javax.swing.JTextField jTextFieldUser;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
